### ISSUE TITLE
How much precision?

### ISSUE THREAD

**Issue by skinnyjames** [skinnyjames/hourglass#2]
How much precision are we using as the dates go way back?

**Comment by Nat34** [comment]
testing if I can reply to this over email, instead of being logged into
Github.

How much precision do you need? I'm sure whatever Javascript provides will
suffice, Date()

**Comment by skinnyjames** [comment]
Hey! will you clone the repo and checkout the test.js file in the `init` branch?

JavaScript can't handle dates far far back, as there was not really any good systems for determining dates from early / pre history.  

The goal of this library is to manipulate dates relative to a calendar date, so we can do things like store dates that are millions of years back.

I'm thinking the cronos object will have methods like getYears, getMonths, getDays, etc.. so we can theoretically have precision down to the second if it's called for.

What do you think?

**Comment by skinnyjames** [comment]
added a function `tickTock` which sets years, months, weeks, hours, minutes, properties.
this way we have all the precision one could likely need from going that far back.
Closing.
